project_id = "tdweqsszaakxhnzbyqar"

[functions.living-resume-ai]
verify_jwt = false

[functions.selfgraph-ai]
verify_jwt = false

[functions.mentor-matchmaking-ai]
verify_jwt = false

[functions.peer-circles-ai]
verify_jwt = false

[functions.project-playground-ai]
verify_jwt = false

[functions.job-matching-ai]
verify_jwt = false

[functions.achievements-ai]
verify_jwt = false